export const ActionTypes = {
  SET_ROBOTS: 'SET_ROBOTS',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  SELECTED_ROBOT: 'SELECTED_ROBOT',
  REMOVE_SELECTED_ROBOT: 'REMOVE_SELECTED_ROBOT'
}
